/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer.Municipios;

import BusinessModelLayer.Entidad;
import BusinessModelLayer.Municipio;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FOSTER
 */
public class frmNuevoMunicipio extends javax.swing.JDialog {

    int idMunicipio = 0;
    private String v;
    private Municipio municipio = new Municipio();
    private Entidad entidad = new Entidad();
    private ArrayList<Integer> idEntidad = new ArrayList<>();
    private ArrayList<Integer> idEntidad2 = new ArrayList<>();

    public frmNuevoMunicipio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public frmNuevoMunicipio() {
        initComponents();
        llenarEntidad();
        cobEntidad.addItemListener(event -> {

            if (event.getStateChange() == ItemEvent.SELECTED) {

                v = (event.getItem().toString());

                municipio.Row(v);

            } else {
                /*
            v = cobEntidad.getSelectedItem().toString();
                 System.out.println(municipio.Row(v).get(0));
                 */
            }
        });

        //cboFar();
        v = cobEntidad.getSelectedItem().toString();

    }

    public frmNuevoMunicipio(int idMunicipio) {
        initComponents();

        this.idMunicipio = idMunicipio;
        municipio.setIdMunicipio(idMunicipio);
        municipio.GetById();
        txtNombre.setText(municipio.getMunicipio());
        llenarEntidad();

        cobEntidad.addItemListener(event -> {

            if (event.getStateChange() == ItemEvent.SELECTED) {

                v = (event.getItem().toString());

                municipio.Row(v);

                //System.out.println( idEntidad = municipio.Row(v));
            }
        });

        cobEntidad.setSelectedIndex(municipio.getIdEntidad() - 1);
        v = cobEntidad.getSelectedItem().toString();
    }

    public void llenarEntidad() {
        DefaultTableModel res = entidad.GetAllModel();
        // DefaultTableModel res2 = municipio.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            cobEntidad.addItem(String.valueOf(res.getValueAt(i, 1)));
            idEntidad.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }

    /*
    public void cboFar() {
        DefaultTableModel res = categorias.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            cboCat.addItem(String.valueOf(res.getValueAt(i, 1)));
            idCategoria.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cobEntidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel1.setText("Nombre:");

        btnOk.setText("Guardar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Entidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(cobEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnOk)
                        .addGap(52, 52, 52)
                        .addComponent(btnCancelar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cobEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        // java.sql.Date date = new java.sql.Date(jDateChooser.getDate().getTime());

        if (municipio.getIdMunicipio() > 0) {
            municipio.setIdEntidad((int) municipio.Row(v).get(0));
            municipio.setMunicipio(txtNombre.getText());
            if (municipio.Update()) {
                JOptionPane.showMessageDialog(null, "Municipio actualizado correctamente");
                this.dispose();
            }
        } else {
            if (new Municipio(0,
                    (int) municipio.Row(v).get(0),
                    txtNombre.getText()).Add()) {
                JOptionPane.showMessageDialog(null, "Municipio agregado correctamente!");
                this.dispose();
            }

        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

//Este metodo agrega los datos del metodo RowData que retorna un arraylist y los coloca en el combo box.
    /*
    public void cboFar() {
        // cboFar.addItem("" + producto.co().get(0));
        for (int i = 0; i < producto.RowData().size(); i++) {
            cboFar.addItem("" + "Far" + " " + producto.RowData().get(i));
        }
    }
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNuevoMunicipio dialog = new frmNuevoMunicipio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cobEntidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
