/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer.ProductosProveedores;

import BusinessModelLayer.Producto;
import BusinessModelLayer.ProductosProveedores;
import BusinessModelLayer.Proveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FOSTER
 */
public class frmNuevoProductoProveedor extends javax.swing.JDialog {

    private int idProductoProveedor = 0;
    ProductosProveedores productoproveedor = new ProductosProveedores();
    private Producto producto = new Producto();
    private Proveedor proveedor = new Proveedor();
    private ArrayList<Integer> idProducto = new ArrayList<>();
    private ArrayList<Integer> idProveedor = new ArrayList<>();

    /**
     * Creates new form frmNuevoProducto
     */
    public frmNuevoProductoProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public frmNuevoProductoProveedor() {
        initComponents();

        llenarProductos();
        llenarProveedores();
    }

    public frmNuevoProductoProveedor(int idProductoProveedor) {
        initComponents();

        idProducto.clear();
        cbProducto.removeAllItems();
        llenarProductos();
        idProveedor.clear();
        cbProveedor.removeAllItems();
        llenarProveedores();

        this.idProductoProveedor = idProductoProveedor;

        productoproveedor.setIdProductoProveedor(idProductoProveedor);
        productoproveedor.GetById();

        producto.setIdProducto(productoproveedor.getIdProducto());
        producto.GetById();
        cbProducto.setSelectedItem(producto.getNombre());

        proveedor.setIdProveedor(productoproveedor.getIdProveedor());
        proveedor.GetById();
        cbProveedor.setSelectedItem(proveedor.getNombre());

    }

    /*
    public void cboFar() {
        DefaultTableModel res = categorias.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            cboCat.addItem(String.valueOf(res.getValueAt(i, 1)));
            idCategoria.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbProveedor = new javax.swing.JComboBox<>();
        cbProducto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel2.setText("Proveedor:");

        btnOk.setText("Guardar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Producto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(77, 77, 77)
                .addComponent(btnCancelar)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarProductos() {
        DefaultTableModel res = producto.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            cbProducto.addItem(String.valueOf(res.getValueAt(i, 1)));
            idProducto.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }

    public void llenarProveedores() {
        DefaultTableModel res = proveedor.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            cbProveedor.addItem(String.valueOf(res.getValueAt(i, 1)));
            idProveedor.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (idProductoProveedor == 0) {
            if (new ProductosProveedores(0,
                    idProveedor.get(cbProveedor.getSelectedIndex()),
                    idProducto.get(cbProducto.getSelectedIndex())).Add() < 0) {
                JOptionPane.showMessageDialog(null, "El Registro ya exite!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Registro exitoso!");
                this.dispose();
            }
        } else {
            productoproveedor.setIdProducto(idProducto.get(cbProducto.getSelectedIndex()));
            productoproveedor.setIdProveedor(idProveedor.get(cbProveedor.getSelectedIndex()));
            if (productoproveedor.Update() < 0) {
                JOptionPane.showMessageDialog(null, "El Registro ya exite!");
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Registro actualizado correctamente!");
                this.dispose();
            }

        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProductoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProductoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProductoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProductoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNuevoProductoProveedor dialog = new frmNuevoProductoProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
