/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import DataAccessLayer.Proveedores.frmProveedor;
import PresentationLayer.Categorias.frmCategorias;
import PresentationLayer.Clientes.frmCliente;
import PresentationLayer.Contactos.frmContacto;
import PresentationLayer.Entidades.frmEntidades;
import PresentationLayer.Localidades.frmLocalidades;
import PresentationLayer.Municipios.frmMunicipios;
import PresentationLayer.Productos.frmProductos;
import PresentationLayer.ProductosProveedores.frmProductoProveedor;
import PresentationLayer.Sucursales.frmSucursal;
import PresentationLayer.Usuarios.frmUsuario;
import java.awt.Dimension;

/**
 *
 * @author FOSTER
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnProductosProveedores = new javax.swing.JMenu();
        btnProductos = new javax.swing.JMenuItem();
        btnCategorias = new javax.swing.JMenuItem();
        btnClientes = new javax.swing.JMenuItem();
        btnContactos = new javax.swing.JMenuItem();
        btnEntidad = new javax.swing.JMenuItem();
        btnMunicipio = new javax.swing.JMenuItem();
        btnLocalidad = new javax.swing.JMenuItem();
        btnProveedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mnArchivo.setText("Archivo");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(btnSalir);

        jMenuBar1.add(mnArchivo);

        btnProductosProveedores.setText("Catalogos");

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnProductos);

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnCategorias);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnClientes);

        btnContactos.setText("Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnContactos);

        btnEntidad.setText("Entidades");
        btnEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntidadActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnEntidad);

        btnMunicipio.setText("Municipios");
        btnMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipioActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnMunicipio);

        btnLocalidad.setText("Localidades");
        btnLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnLocalidad);

        btnProveedor.setText("Proveedores");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnProveedor);

        jMenuItem1.setText("Sucursales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(jMenuItem1);

        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnUsuario);

        jMenuItem2.setText("ProductosProveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(jMenuItem2);

        jMenuBar1.add(btnProductosProveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        frmProductos obj = new frmProductos();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnProductosActionPerformed


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
        frmCategorias obj = new frmCategorias();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        frmCliente obj = new frmCliente();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        // TODO add your handling code here:
        frmContacto obj = new frmContacto();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntidadActionPerformed
        // TODO add your handling code here:
        frmEntidades obj = new frmEntidades();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnEntidadActionPerformed

    private void btnMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipioActionPerformed
        // TODO add your handling code here:
        frmMunicipios obj = new frmMunicipios();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnMunicipioActionPerformed

    private void btnLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadActionPerformed
        // TODO add your handling code here:
        frmLocalidades obj = new frmLocalidades();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnLocalidadActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        frmProveedor obj = new frmProveedor();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmSucursal obj = new frmSucursal();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        frmUsuario obj = new frmUsuario();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmProductoProveedor obj = new frmProductoProveedor();
        DesktopPane.add(obj);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 3);
        obj.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem btnCategorias;
    private javax.swing.JMenuItem btnClientes;
    private javax.swing.JMenuItem btnContactos;
    private javax.swing.JMenuItem btnEntidad;
    private javax.swing.JMenuItem btnLocalidad;
    private javax.swing.JMenuItem btnMunicipio;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenu btnProductosProveedores;
    private javax.swing.JMenuItem btnProveedor;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnArchivo;
    // End of variables declaration//GEN-END:variables
}
